"""replace base_price with weekday/weekend/holiday pricing

Revision ID: 036e4d01f8d1
Revises: 229c893c3969
Create Date: 2026-07-26 15:48:45.858592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036e4d01f8d1'
down_revision: Union[str, Sequence[str], None] = '229c893c3969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('label', sa.String(), nullable=False))
    op.drop_column('pricing_rules', 'fixed_price')
    op.drop_column('pricing_rules', 'price_multiplier')
    op.add_column('room_types', sa.Column('weekday_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('room_types', sa.Column('weekend_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('room_types', sa.Column('holiday_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('room_types', 'base_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('room_types', 'holiday_price')
    op.drop_column('room_types', 'weekend_price')
    op.drop_column('room_types', 'weekday_price')
    op.add_column('pricing_rules', sa.Column('price_multiplier', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('pricing_rules', sa.Column('fixed_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('pricing_rules', 'label')
    # ### end Alembic commands ###
